### PR TITLE
feat: create Newsletter section

### PR DESCRIPTION
**Pull request by mihrab34**
PR not on main Repo

### CODE REVIEW

**Comment by CatherineKiiru** [comment]
Hi @mihrab34 I can't see your branch when I do git pull. Did you sync your fork to the main branch?

**Comment by mihrab34** [comment]
@CatherineKiiru yes i did. But the PR is on branch **newsletter-section**

**Comment by CatherineKiiru** [comment]
Hi @mihrab34 it's showing that you've pushed your changes to the forked repo, not the main repo. That's why I can't access your branch

**Comment by mihrab34** [comment]
> Hi @mihrab34 it's showing that you've pushed your changes to the forked repo, not the main repo. That's why I can't access your branch

yeah, i'll just push the changes to a new branch on this repo and open a new PR with it. i've added a new PR from a branch on the main repo. I'll close this PR

**Pull request closed without merging**
